# db for local dev
version: '3.9'

services:
  postgresql:
    image: postgres:13.4-alpine # latest version supported by aws
    container_name: pg-devices-api
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dimo
      - POSTGRES_PASSWORD=dimo
      - POSTGRES_DB=devices_api
    volumes:
      - ./resources/data:/var/lib/postgresql/data:delegated