PORT: 3000
LOG_LEVEL: info
DB_USER: dimo
DB_PASSWORD: dimo
DB_PORT: 5432
DB_HOST: localhost
DB_NAME: devices_api
DB_MAX_OPEN_CONNECTIONS: 5
DB_MAX_IDLE_CONNECTIONS: 5
SERVICE_NAME: devices-api
JWT_KEY_SET_URL: http://127.0.0.1:5556/dex/keys
SWAGGER_BASE_URL: http://localhost:3000