apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "devices-api.fullname" . }}
  labels:
    {{- include "devices-api.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace}}
  podMetricsEndpoints:
  - path: /metrics
    port: http
  selector:
    matchLabels:
      {{- include "devices-api.selectorLabels" . | nindent 6 }}