package controllers

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"
	"testing"

	"github.com/DIMO-Network/devices-api/internal/config"
	"github.com/DIMO-Network/devices-api/internal/services"
	"github.com/DIMO-Network/devices-api/internal/test"
	"github.com/DIMO-Network/devices-api/models"
	"github.com/gofiber/fiber/v2"
	"github.com/segmentio/ksuid"
	"github.com/stretchr/testify/assert"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
)

func TestWebhooksController_ProcessCommand(t *testing.T) {
	ctx := context.Background()
	pdb := test.GetDBConnection(ctx)

	token := "BobbyHarry"
	c := NewWebhooksController(&config.Settings{AutoPiAPIToken: token}, pdb.DBS)
	app := fiber.New()
	app.Post(services.AutoPiWebhookPath, c.ProcessCommand)

	t.Run("POST - webhook request 401 with invalid signature", func(t *testing.T) {
		awp := &AutoPiWebhookPayload{
			Jid:      "autoPiJobId", // needs to match db for work
			State:    "COMMAND_EXECUTED",
			Success:  true,
			DeviceID: 11, // must match DB for it to work
		}
		j, _ := json.Marshal(awp)

		request := test.BuildRequest("POST", services.AutoPiWebhookPath, string(j))
		request.Header.Set("X-Request-Signature", "") // copy this from replit python generated value
		response, _ := app.Test(request)
		// assert
		assert.Equal(t, 401, response.StatusCode)
	})
	t.Run("POST - webhook request", func(t *testing.T) {
		// arrange
		testUserID := ksuid.New().String()
		autoPiDeviceID := 123123
		autoPiTemplateID := 987
		autoPiJobID := "AD111"
		dm := test.SetupCreateMake(t, "Testla", pdb)
		dd := test.SetupCreateDeviceDefinition(t, dm, "Model X", 2022, pdb)
		integ := test.SetupCreateAutoPiIntegration(t, autoPiTemplateID, pdb)
		ud := test.SetupCreateUserDevice(t, testUserID, dd, pdb)
		test.SetupCreateDeviceIntegration(t, dd, integ, ud, pdb)
		// create user device api integration
		m := new(services.UserDeviceAPIIntegrationsMetadata)
		m.AutoPiSyncCommandJobID = &autoPiJobID
		udiai := models.UserDeviceAPIIntegration{
			UserDeviceID:  ud.ID,
			IntegrationID: integ.ID,
			Status:        models.UserDeviceAPIIntegrationStatusPending,
			ExternalID:    null.StringFrom(strconv.Itoa(autoPiDeviceID)),
		}
		err := udiai.Metadata.Marshal(m)
		assert.NoError(t, err)
		err = udiai.Insert(ctx, pdb.DBS().Writer, boil.Infer())
		assert.NoError(t, err)

		// act
		awp := &AutoPiWebhookPayload{
			Jid:      autoPiJobID, // needs to match db for work
			State:    "COMMAND_EXECUTED",
			Success:  true,
			DeviceID: autoPiDeviceID, // must match DB for it to work
		}
		j, _ := json.Marshal(awp)
		fmt.Println(string(j))

		request := test.BuildRequest("POST", services.AutoPiWebhookPath, string(j))
		// signature generated by python per example code from autopi (for above payload)
		request.Header.Set("X-Request-Signature", "245dd949a5e3fae47b596ad418dab6ac7ed09516eafe95afae1b8080fb5aa0e6")
		response, _ := app.Test(request)
		// assert
		assert.Equal(t, 204, response.StatusCode)
		// check the database has the expected change in status, and `auto_pi_sync_command_state` in metadata
		updatedUdiai, err := models.UserDeviceAPIIntegrations(
			models.UserDeviceAPIIntegrationWhere.UserDeviceID.EQ(ud.ID),
			models.UserDeviceAPIIntegrationWhere.IntegrationID.EQ(integ.ID)).
			One(ctx, pdb.DBS().Writer)
		assert.NoError(t, err)

		assert.Equal(t, models.UserDeviceAPIIntegrationStatusPendingFirstData, updatedUdiai.Status)

		_ = updatedUdiai.Metadata.Unmarshal(m)
		assert.Equal(t, awp.State, *m.AutoPiSyncCommandState)
		assert.Equal(t, awp.Jid, *m.AutoPiSyncCommandJobID)

		// teardown
		test.TruncateTables(pdb.DBS().Writer.DB, t)
	})

}
