replicaCount: 1
image:
  repository: dimozone/devices-api
  pullPolicy: Always
  tag: 29e2bb5
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
env:
  PORT: '8080'
  LOG_LEVEL: info
  DB_PORT: '5432'
  DB_HOST: dimo-database-dev.csxmknv0wp9n.us-east-2.rds.amazonaws.com
  DB_NAME: devices_api
  DB_MAX_OPEN_CONNECTIONS: '10'
  DB_MAX_IDLE_CONNECTIONS: '3'
  SERVICE_NAME: devices-api
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: devices-api.dev.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
