// Code generated by MockGen. DO NOT EDIT.
// Source: tesla_service.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	reflect "reflect"

	services "github.com/DIMO-INC/devices-api/internal/services"
	gomock "github.com/golang/mock/gomock"
)

// MockTeslaService is a mock of TeslaService interface.
type MockTeslaService struct {
	ctrl     *gomock.Controller
	recorder *MockTeslaServiceMockRecorder
}

// MockTeslaServiceMockRecorder is the mock recorder for MockTeslaService.
type MockTeslaServiceMockRecorder struct {
	mock *MockTeslaService
}

// NewMockTeslaService creates a new mock instance.
func NewMockTeslaService(ctrl *gomock.Controller) *MockTeslaService {
	mock := &MockTeslaService{ctrl: ctrl}
	mock.recorder = &MockTeslaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeslaService) EXPECT() *MockTeslaServiceMockRecorder {
	return m.recorder
}

// GetVehicle mocks base method.
func (m *MockTeslaService) GetVehicle(ownerAccessToken string, id int) (*services.TeslaVehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehicle", ownerAccessToken, id)
	ret0, _ := ret[0].(*services.TeslaVehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehicle indicates an expected call of GetVehicle.
func (mr *MockTeslaServiceMockRecorder) GetVehicle(ownerAccessToken, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicle", reflect.TypeOf((*MockTeslaService)(nil).GetVehicle), ownerAccessToken, id)
}
