name: buildpush
on:
  push:
    tags:
      - v*
  pull_request:

jobs:
  build_test:
    # The type of runner that the job will run on
    name: buildpush
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - uses: tenhaus/get-release-or-tag@v2
        id: tag
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./resources/docker/Dockerfile
          push: true
          tags: dimozone/devices-api:${{ steps.tag.outputs.tag }}

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'charts/devices-api/values-prod.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.tag.outputs.tag }}
          branch: main
          message: 'Update Prod Image Version to ${{ steps.tag.outputs.tag }}'