name: buildpush
on:
  push:
    tags:
      - v*
  pull_request:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    # The type of runner that the job will run on
    name: buildpush
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./resources/docker/Dockerfile
          push: true
          tags: dimozone/devices-api:latest
          
      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'charts/helm/values-prod.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.image.outputs.version }}
          branch: main
          message: 'Update Image Version to ${{ steps.image.outputs.version }}'