name: buildpush
on:
  push:
    tags:
      - v*
  pull_request:

jobs:
  build_test:
    # The type of runner that the job will run on
    name: buildpush
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./resources/docker/Dockerfile
          push: true
          tags: dimozone/devices-api:${{ env.GITHUB_REF_NAME }}, dimozone/devices-api:latest

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'charts/devices-api/values-prod.yaml'
          propertyPath: 'image.tag'
          value: ${{ env.GITHUB_REF_NAME }}
          branch: main
          message: 'Update Prod Image Version to ${{ env.GITHUB_REF_NAME }}'