// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// AutopiUnit is an object representing the database table.
type AutopiUnit struct {
	AutopiUnitID   string      `boil:"autopi_unit_id" json:"autopi_unit_id" toml:"autopi_unit_id" yaml:"autopi_unit_id"`
	AutopiDeviceID null.String `boil:"autopi_device_id" json:"autopi_device_id,omitempty" toml:"autopi_device_id" yaml:"autopi_device_id,omitempty"`
	UserID         string      `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	NFTAddress     null.String `boil:"nft_address" json:"nft_address,omitempty" toml:"nft_address" yaml:"nft_address,omitempty"`
	CreatedAt      time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt      time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *autopiUnitR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L autopiUnitL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AutopiUnitColumns = struct {
	AutopiUnitID   string
	AutopiDeviceID string
	UserID         string
	NFTAddress     string
	CreatedAt      string
	UpdatedAt      string
}{
	AutopiUnitID:   "autopi_unit_id",
	AutopiDeviceID: "autopi_device_id",
	UserID:         "user_id",
	NFTAddress:     "nft_address",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}

var AutopiUnitTableColumns = struct {
	AutopiUnitID   string
	AutopiDeviceID string
	UserID         string
	NFTAddress     string
	CreatedAt      string
	UpdatedAt      string
}{
	AutopiUnitID:   "autopi_units.autopi_unit_id",
	AutopiDeviceID: "autopi_units.autopi_device_id",
	UserID:         "autopi_units.user_id",
	NFTAddress:     "autopi_units.nft_address",
	CreatedAt:      "autopi_units.created_at",
	UpdatedAt:      "autopi_units.updated_at",
}

// Generated where

var AutopiUnitWhere = struct {
	AutopiUnitID   whereHelperstring
	AutopiDeviceID whereHelpernull_String
	UserID         whereHelperstring
	NFTAddress     whereHelpernull_String
	CreatedAt      whereHelpertime_Time
	UpdatedAt      whereHelpertime_Time
}{
	AutopiUnitID:   whereHelperstring{field: "\"devices_api\".\"autopi_units\".\"autopi_unit_id\""},
	AutopiDeviceID: whereHelpernull_String{field: "\"devices_api\".\"autopi_units\".\"autopi_device_id\""},
	UserID:         whereHelperstring{field: "\"devices_api\".\"autopi_units\".\"user_id\""},
	NFTAddress:     whereHelpernull_String{field: "\"devices_api\".\"autopi_units\".\"nft_address\""},
	CreatedAt:      whereHelpertime_Time{field: "\"devices_api\".\"autopi_units\".\"created_at\""},
	UpdatedAt:      whereHelpertime_Time{field: "\"devices_api\".\"autopi_units\".\"updated_at\""},
}

// AutopiUnitRels is where relationship names are stored.
var AutopiUnitRels = struct {
	AutopiJobs                string
	UserDeviceAPIIntegrations string
}{
	AutopiJobs:                "AutopiJobs",
	UserDeviceAPIIntegrations: "UserDeviceAPIIntegrations",
}

// autopiUnitR is where relationships are stored.
type autopiUnitR struct {
	AutopiJobs                AutopiJobSlice                `boil:"AutopiJobs" json:"AutopiJobs" toml:"AutopiJobs" yaml:"AutopiJobs"`
	UserDeviceAPIIntegrations UserDeviceAPIIntegrationSlice `boil:"UserDeviceAPIIntegrations" json:"UserDeviceAPIIntegrations" toml:"UserDeviceAPIIntegrations" yaml:"UserDeviceAPIIntegrations"`
}

// NewStruct creates a new relationship struct
func (*autopiUnitR) NewStruct() *autopiUnitR {
	return &autopiUnitR{}
}

// autopiUnitL is where Load methods for each relationship are stored.
type autopiUnitL struct{}

var (
	autopiUnitAllColumns            = []string{"autopi_unit_id", "autopi_device_id", "user_id", "nft_address", "created_at", "updated_at"}
	autopiUnitColumnsWithoutDefault = []string{"autopi_unit_id", "user_id"}
	autopiUnitColumnsWithDefault    = []string{"autopi_device_id", "nft_address", "created_at", "updated_at"}
	autopiUnitPrimaryKeyColumns     = []string{"autopi_unit_id"}
	autopiUnitGeneratedColumns      = []string{}
)

type (
	// AutopiUnitSlice is an alias for a slice of pointers to AutopiUnit.
	// This should almost always be used instead of []AutopiUnit.
	AutopiUnitSlice []*AutopiUnit
	// AutopiUnitHook is the signature for custom AutopiUnit hook methods
	AutopiUnitHook func(context.Context, boil.ContextExecutor, *AutopiUnit) error

	autopiUnitQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	autopiUnitType                 = reflect.TypeOf(&AutopiUnit{})
	autopiUnitMapping              = queries.MakeStructMapping(autopiUnitType)
	autopiUnitPrimaryKeyMapping, _ = queries.BindMapping(autopiUnitType, autopiUnitMapping, autopiUnitPrimaryKeyColumns)
	autopiUnitInsertCacheMut       sync.RWMutex
	autopiUnitInsertCache          = make(map[string]insertCache)
	autopiUnitUpdateCacheMut       sync.RWMutex
	autopiUnitUpdateCache          = make(map[string]updateCache)
	autopiUnitUpsertCacheMut       sync.RWMutex
	autopiUnitUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var autopiUnitAfterSelectHooks []AutopiUnitHook

var autopiUnitBeforeInsertHooks []AutopiUnitHook
var autopiUnitAfterInsertHooks []AutopiUnitHook

var autopiUnitBeforeUpdateHooks []AutopiUnitHook
var autopiUnitAfterUpdateHooks []AutopiUnitHook

var autopiUnitBeforeDeleteHooks []AutopiUnitHook
var autopiUnitAfterDeleteHooks []AutopiUnitHook

var autopiUnitBeforeUpsertHooks []AutopiUnitHook
var autopiUnitAfterUpsertHooks []AutopiUnitHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AutopiUnit) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range autopiUnitAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AutopiUnit) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range autopiUnitBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AutopiUnit) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range autopiUnitAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AutopiUnit) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range autopiUnitBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AutopiUnit) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range autopiUnitAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AutopiUnit) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range autopiUnitBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AutopiUnit) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range autopiUnitAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AutopiUnit) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range autopiUnitBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AutopiUnit) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range autopiUnitAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAutopiUnitHook registers your hook function for all future operations.
func AddAutopiUnitHook(hookPoint boil.HookPoint, autopiUnitHook AutopiUnitHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		autopiUnitAfterSelectHooks = append(autopiUnitAfterSelectHooks, autopiUnitHook)
	case boil.BeforeInsertHook:
		autopiUnitBeforeInsertHooks = append(autopiUnitBeforeInsertHooks, autopiUnitHook)
	case boil.AfterInsertHook:
		autopiUnitAfterInsertHooks = append(autopiUnitAfterInsertHooks, autopiUnitHook)
	case boil.BeforeUpdateHook:
		autopiUnitBeforeUpdateHooks = append(autopiUnitBeforeUpdateHooks, autopiUnitHook)
	case boil.AfterUpdateHook:
		autopiUnitAfterUpdateHooks = append(autopiUnitAfterUpdateHooks, autopiUnitHook)
	case boil.BeforeDeleteHook:
		autopiUnitBeforeDeleteHooks = append(autopiUnitBeforeDeleteHooks, autopiUnitHook)
	case boil.AfterDeleteHook:
		autopiUnitAfterDeleteHooks = append(autopiUnitAfterDeleteHooks, autopiUnitHook)
	case boil.BeforeUpsertHook:
		autopiUnitBeforeUpsertHooks = append(autopiUnitBeforeUpsertHooks, autopiUnitHook)
	case boil.AfterUpsertHook:
		autopiUnitAfterUpsertHooks = append(autopiUnitAfterUpsertHooks, autopiUnitHook)
	}
}

// One returns a single autopiUnit record from the query.
func (q autopiUnitQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AutopiUnit, error) {
	o := &AutopiUnit{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for autopi_units")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AutopiUnit records from the query.
func (q autopiUnitQuery) All(ctx context.Context, exec boil.ContextExecutor) (AutopiUnitSlice, error) {
	var o []*AutopiUnit

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AutopiUnit slice")
	}

	if len(autopiUnitAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AutopiUnit records in the query.
func (q autopiUnitQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count autopi_units rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q autopiUnitQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if autopi_units exists")
	}

	return count > 0, nil
}

// AutopiJobs retrieves all the autopi_job's AutopiJobs with an executor.
func (o *AutopiUnit) AutopiJobs(mods ...qm.QueryMod) autopiJobQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"devices_api\".\"autopi_jobs\".\"autopi_unit_id\"=?", o.AutopiUnitID),
	)

	query := AutopiJobs(queryMods...)
	queries.SetFrom(query.Query, "\"devices_api\".\"autopi_jobs\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"devices_api\".\"autopi_jobs\".*"})
	}

	return query
}

// UserDeviceAPIIntegrations retrieves all the user_device_api_integration's UserDeviceAPIIntegrations with an executor.
func (o *AutopiUnit) UserDeviceAPIIntegrations(mods ...qm.QueryMod) userDeviceAPIIntegrationQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"devices_api\".\"user_device_api_integrations\".\"autopi_unit_id\"=?", o.AutopiUnitID),
	)

	query := UserDeviceAPIIntegrations(queryMods...)
	queries.SetFrom(query.Query, "\"devices_api\".\"user_device_api_integrations\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"devices_api\".\"user_device_api_integrations\".*"})
	}

	return query
}

// LoadAutopiJobs allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (autopiUnitL) LoadAutopiJobs(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAutopiUnit interface{}, mods queries.Applicator) error {
	var slice []*AutopiUnit
	var object *AutopiUnit

	if singular {
		object = maybeAutopiUnit.(*AutopiUnit)
	} else {
		slice = *maybeAutopiUnit.(*[]*AutopiUnit)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &autopiUnitR{}
		}
		args = append(args, object.AutopiUnitID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &autopiUnitR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.AutopiUnitID) {
					continue Outer
				}
			}

			args = append(args, obj.AutopiUnitID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`devices_api.autopi_jobs`),
		qm.WhereIn(`devices_api.autopi_jobs.autopi_unit_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load autopi_jobs")
	}

	var resultSlice []*AutopiJob
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice autopi_jobs")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on autopi_jobs")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for autopi_jobs")
	}

	if len(autopiJobAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.AutopiJobs = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &autopiJobR{}
			}
			foreign.R.AutopiUnit = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.AutopiUnitID, foreign.AutopiUnitID) {
				local.R.AutopiJobs = append(local.R.AutopiJobs, foreign)
				if foreign.R == nil {
					foreign.R = &autopiJobR{}
				}
				foreign.R.AutopiUnit = local
				break
			}
		}
	}

	return nil
}

// LoadUserDeviceAPIIntegrations allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (autopiUnitL) LoadUserDeviceAPIIntegrations(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAutopiUnit interface{}, mods queries.Applicator) error {
	var slice []*AutopiUnit
	var object *AutopiUnit

	if singular {
		object = maybeAutopiUnit.(*AutopiUnit)
	} else {
		slice = *maybeAutopiUnit.(*[]*AutopiUnit)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &autopiUnitR{}
		}
		args = append(args, object.AutopiUnitID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &autopiUnitR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.AutopiUnitID) {
					continue Outer
				}
			}

			args = append(args, obj.AutopiUnitID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`devices_api.user_device_api_integrations`),
		qm.WhereIn(`devices_api.user_device_api_integrations.autopi_unit_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load user_device_api_integrations")
	}

	var resultSlice []*UserDeviceAPIIntegration
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice user_device_api_integrations")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on user_device_api_integrations")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for user_device_api_integrations")
	}

	if len(userDeviceAPIIntegrationAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.UserDeviceAPIIntegrations = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &userDeviceAPIIntegrationR{}
			}
			foreign.R.AutopiUnit = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.AutopiUnitID, foreign.AutopiUnitID) {
				local.R.UserDeviceAPIIntegrations = append(local.R.UserDeviceAPIIntegrations, foreign)
				if foreign.R == nil {
					foreign.R = &userDeviceAPIIntegrationR{}
				}
				foreign.R.AutopiUnit = local
				break
			}
		}
	}

	return nil
}

// AddAutopiJobs adds the given related objects to the existing relationships
// of the autopi_unit, optionally inserting them as new records.
// Appends related to o.R.AutopiJobs.
// Sets related.R.AutopiUnit appropriately.
func (o *AutopiUnit) AddAutopiJobs(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*AutopiJob) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.AutopiUnitID, o.AutopiUnitID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"devices_api\".\"autopi_jobs\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"autopi_unit_id"}),
				strmangle.WhereClause("\"", "\"", 2, autopiJobPrimaryKeyColumns),
			)
			values := []interface{}{o.AutopiUnitID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.AutopiUnitID, o.AutopiUnitID)
		}
	}

	if o.R == nil {
		o.R = &autopiUnitR{
			AutopiJobs: related,
		}
	} else {
		o.R.AutopiJobs = append(o.R.AutopiJobs, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &autopiJobR{
				AutopiUnit: o,
			}
		} else {
			rel.R.AutopiUnit = o
		}
	}
	return nil
}

// SetAutopiJobs removes all previously related items of the
// autopi_unit replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.AutopiUnit's AutopiJobs accordingly.
// Replaces o.R.AutopiJobs with related.
// Sets related.R.AutopiUnit's AutopiJobs accordingly.
func (o *AutopiUnit) SetAutopiJobs(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*AutopiJob) error {
	query := "update \"devices_api\".\"autopi_jobs\" set \"autopi_unit_id\" = null where \"autopi_unit_id\" = $1"
	values := []interface{}{o.AutopiUnitID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.AutopiJobs {
			queries.SetScanner(&rel.AutopiUnitID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.AutopiUnit = nil
		}

		o.R.AutopiJobs = nil
	}
	return o.AddAutopiJobs(ctx, exec, insert, related...)
}

// RemoveAutopiJobs relationships from objects passed in.
// Removes related items from R.AutopiJobs (uses pointer comparison, removal does not keep order)
// Sets related.R.AutopiUnit.
func (o *AutopiUnit) RemoveAutopiJobs(ctx context.Context, exec boil.ContextExecutor, related ...*AutopiJob) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.AutopiUnitID, nil)
		if rel.R != nil {
			rel.R.AutopiUnit = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("autopi_unit_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.AutopiJobs {
			if rel != ri {
				continue
			}

			ln := len(o.R.AutopiJobs)
			if ln > 1 && i < ln-1 {
				o.R.AutopiJobs[i] = o.R.AutopiJobs[ln-1]
			}
			o.R.AutopiJobs = o.R.AutopiJobs[:ln-1]
			break
		}
	}

	return nil
}

// AddUserDeviceAPIIntegrations adds the given related objects to the existing relationships
// of the autopi_unit, optionally inserting them as new records.
// Appends related to o.R.UserDeviceAPIIntegrations.
// Sets related.R.AutopiUnit appropriately.
func (o *AutopiUnit) AddUserDeviceAPIIntegrations(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*UserDeviceAPIIntegration) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.AutopiUnitID, o.AutopiUnitID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"devices_api\".\"user_device_api_integrations\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"autopi_unit_id"}),
				strmangle.WhereClause("\"", "\"", 2, userDeviceAPIIntegrationPrimaryKeyColumns),
			)
			values := []interface{}{o.AutopiUnitID, rel.UserDeviceID, rel.IntegrationID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.AutopiUnitID, o.AutopiUnitID)
		}
	}

	if o.R == nil {
		o.R = &autopiUnitR{
			UserDeviceAPIIntegrations: related,
		}
	} else {
		o.R.UserDeviceAPIIntegrations = append(o.R.UserDeviceAPIIntegrations, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &userDeviceAPIIntegrationR{
				AutopiUnit: o,
			}
		} else {
			rel.R.AutopiUnit = o
		}
	}
	return nil
}

// SetUserDeviceAPIIntegrations removes all previously related items of the
// autopi_unit replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.AutopiUnit's UserDeviceAPIIntegrations accordingly.
// Replaces o.R.UserDeviceAPIIntegrations with related.
// Sets related.R.AutopiUnit's UserDeviceAPIIntegrations accordingly.
func (o *AutopiUnit) SetUserDeviceAPIIntegrations(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*UserDeviceAPIIntegration) error {
	query := "update \"devices_api\".\"user_device_api_integrations\" set \"autopi_unit_id\" = null where \"autopi_unit_id\" = $1"
	values := []interface{}{o.AutopiUnitID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.UserDeviceAPIIntegrations {
			queries.SetScanner(&rel.AutopiUnitID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.AutopiUnit = nil
		}

		o.R.UserDeviceAPIIntegrations = nil
	}
	return o.AddUserDeviceAPIIntegrations(ctx, exec, insert, related...)
}

// RemoveUserDeviceAPIIntegrations relationships from objects passed in.
// Removes related items from R.UserDeviceAPIIntegrations (uses pointer comparison, removal does not keep order)
// Sets related.R.AutopiUnit.
func (o *AutopiUnit) RemoveUserDeviceAPIIntegrations(ctx context.Context, exec boil.ContextExecutor, related ...*UserDeviceAPIIntegration) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.AutopiUnitID, nil)
		if rel.R != nil {
			rel.R.AutopiUnit = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("autopi_unit_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.UserDeviceAPIIntegrations {
			if rel != ri {
				continue
			}

			ln := len(o.R.UserDeviceAPIIntegrations)
			if ln > 1 && i < ln-1 {
				o.R.UserDeviceAPIIntegrations[i] = o.R.UserDeviceAPIIntegrations[ln-1]
			}
			o.R.UserDeviceAPIIntegrations = o.R.UserDeviceAPIIntegrations[:ln-1]
			break
		}
	}

	return nil
}

// AutopiUnits retrieves all the records using an executor.
func AutopiUnits(mods ...qm.QueryMod) autopiUnitQuery {
	mods = append(mods, qm.From("\"devices_api\".\"autopi_units\""))
	return autopiUnitQuery{NewQuery(mods...)}
}

// FindAutopiUnit retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAutopiUnit(ctx context.Context, exec boil.ContextExecutor, autopiUnitID string, selectCols ...string) (*AutopiUnit, error) {
	autopiUnitObj := &AutopiUnit{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"devices_api\".\"autopi_units\" where \"autopi_unit_id\"=$1", sel,
	)

	q := queries.Raw(query, autopiUnitID)

	err := q.Bind(ctx, exec, autopiUnitObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from autopi_units")
	}

	if err = autopiUnitObj.doAfterSelectHooks(ctx, exec); err != nil {
		return autopiUnitObj, err
	}

	return autopiUnitObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AutopiUnit) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no autopi_units provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(autopiUnitColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	autopiUnitInsertCacheMut.RLock()
	cache, cached := autopiUnitInsertCache[key]
	autopiUnitInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			autopiUnitAllColumns,
			autopiUnitColumnsWithDefault,
			autopiUnitColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(autopiUnitType, autopiUnitMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(autopiUnitType, autopiUnitMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"devices_api\".\"autopi_units\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"devices_api\".\"autopi_units\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into autopi_units")
	}

	if !cached {
		autopiUnitInsertCacheMut.Lock()
		autopiUnitInsertCache[key] = cache
		autopiUnitInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AutopiUnit.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AutopiUnit) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	autopiUnitUpdateCacheMut.RLock()
	cache, cached := autopiUnitUpdateCache[key]
	autopiUnitUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			autopiUnitAllColumns,
			autopiUnitPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update autopi_units, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"devices_api\".\"autopi_units\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, autopiUnitPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(autopiUnitType, autopiUnitMapping, append(wl, autopiUnitPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update autopi_units row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for autopi_units")
	}

	if !cached {
		autopiUnitUpdateCacheMut.Lock()
		autopiUnitUpdateCache[key] = cache
		autopiUnitUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q autopiUnitQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for autopi_units")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for autopi_units")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AutopiUnitSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), autopiUnitPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"devices_api\".\"autopi_units\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, autopiUnitPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in autopiUnit slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all autopiUnit")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AutopiUnit) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no autopi_units provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(autopiUnitColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	autopiUnitUpsertCacheMut.RLock()
	cache, cached := autopiUnitUpsertCache[key]
	autopiUnitUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			autopiUnitAllColumns,
			autopiUnitColumnsWithDefault,
			autopiUnitColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			autopiUnitAllColumns,
			autopiUnitPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert autopi_units, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(autopiUnitPrimaryKeyColumns))
			copy(conflict, autopiUnitPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"devices_api\".\"autopi_units\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(autopiUnitType, autopiUnitMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(autopiUnitType, autopiUnitMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert autopi_units")
	}

	if !cached {
		autopiUnitUpsertCacheMut.Lock()
		autopiUnitUpsertCache[key] = cache
		autopiUnitUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AutopiUnit record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AutopiUnit) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AutopiUnit provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), autopiUnitPrimaryKeyMapping)
	sql := "DELETE FROM \"devices_api\".\"autopi_units\" WHERE \"autopi_unit_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from autopi_units")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for autopi_units")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q autopiUnitQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no autopiUnitQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from autopi_units")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for autopi_units")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AutopiUnitSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(autopiUnitBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), autopiUnitPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"devices_api\".\"autopi_units\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, autopiUnitPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from autopiUnit slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for autopi_units")
	}

	if len(autopiUnitAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AutopiUnit) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAutopiUnit(ctx, exec, o.AutopiUnitID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AutopiUnitSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AutopiUnitSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), autopiUnitPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"devices_api\".\"autopi_units\".* FROM \"devices_api\".\"autopi_units\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, autopiUnitPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AutopiUnitSlice")
	}

	*o = slice

	return nil
}

// AutopiUnitExists checks if the AutopiUnit row exists.
func AutopiUnitExists(ctx context.Context, exec boil.ContextExecutor, autopiUnitID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"devices_api\".\"autopi_units\" where \"autopi_unit_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, autopiUnitID)
	}
	row := exec.QueryRowContext(ctx, sql, autopiUnitID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if autopi_units exists")
	}

	return exists, nil
}
