// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DeviceDefinitions  string
	DeviceIntegrations string
	Integrations       string
	UserDevices        string
}{
	DeviceDefinitions:  "device_definitions",
	DeviceIntegrations: "device_integrations",
	Integrations:       "integrations",
	UserDevices:        "user_devices",
}
