// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DeviceDefinitions         string
	DeviceIntegrations        string
	DeviceMakes               string
	DeviceStyles              string
	Geofences                 string
	Integrations              string
	UserDeviceAPIIntegrations string
	UserDeviceData            string
	UserDeviceToGeofence      string
	UserDevices               string
}{
	DeviceDefinitions:         "device_definitions",
	DeviceIntegrations:        "device_integrations",
	DeviceMakes:               "device_makes",
	DeviceStyles:              "device_styles",
	Geofences:                 "geofences",
	Integrations:              "integrations",
	UserDeviceAPIIntegrations: "user_device_api_integrations",
	UserDeviceData:            "user_device_data",
	UserDeviceToGeofence:      "user_device_to_geofence",
	UserDevices:               "user_devices",
}
